import { SiteContent } from "../interfaces";
import { contactEmail } from "./shared";

const legalUpdated = 'Stand: September 2026';

export const de: SiteContent = {
  meta: {
    title: 'Christian Dechant | Senior Full-Stack & Applied AI Engineer',
    description: 'Christian Dechant, M.Sc. Angewandte Informatik – Senior Full-Stack Developer mit 9+ Jahren Erfahrung in C#, Next.js & TypeScript. Web- & Softwareentwicklung, AI Consulting, Entwickler-Coaching und Gründer von WayVenture.',
    ogLocale: 'de_DE',
    siteName: 'Christian Dechant',
    keywords: [
      'Christian Dechant',
      'Freelance Entwickler',
      'Full-Stack Entwickler',
      'Webentwickler',
      'App Entwickler',
      'C# Entwickler',
      'Next.js Entwickler',
      'Software Freelancer Fulda',
      'AI Consulting',
      'KI Beratung',
      'KI-Agenten Entwicklung',
      'Entwickler Coaching KI',
    ],
    jobTitle: 'Senior Full-Stack & Applied AI Engineer',
  },
  header: {
    tagline: 'Full-Stack & Applied AI',
    badge: 'Senior Dev',
    nav: [
      { href: '#about', title: 'Über mich', mobileTitle: 'Über mich' },
      { href: '#wayventure', title: 'WayVenture', mobileTitle: 'WayVenture (App)', highlight: 'amber', badge: 'Live' },
      { href: '#services', title: 'Angebote', mobileTitle: 'Angebote & Webpakete' },
      { href: '#ai-consulting', title: 'AI Consulting', mobileTitle: 'AI Consulting & Coaching' },
      { href: '#experience', title: 'Erfahrung', mobileTitle: 'Erfahrung & Werdegang' },
      { href: '#feuerwehr', title: 'Ehrenamt', mobileTitle: 'Ehrenamt Feuerwehr', highlight: 'rose' },
      { href: '#contact', title: 'Kontakt', mobileTitle: 'Kontakt' },
    ],
    cta: 'Projekt anfragen',
    mobileCta: 'Projekt starten',
    drawerTitle: 'Navigation',
    openMenu: 'Navigation öffnen',
    closeMenu: 'Navigation schließen',
    languageLabel: 'Sprache wählen',
  },
  hero: {
    status: 'Verfügbar für ausgewählte Projekte & AI-Engineering',
    headline: 'Senior Engineering & Pragmatische KI —',
    headlineHighlight: 'gebaut für echte Wirkung.',
    intro: 'Hi, ich bin **Christian Dechant**, M.Sc. Angewandte Informatik. Als Senior Full-Stack Developer bei *Strauss GmbH & Co. KG* und Gründer von *WayVenture* verbinde ich 9+ Jahre industrielle Softwarearchitektur (C#, Next.js, Cloud) mit deterministischer, agentischer KI-Entwicklung.',
    primaryCta: 'Projekt anfragen',
    secondaryCta: 'WayVenture entdecken',
    stats: [
      { value: '9+ Jahre', label: 'Software Engineering' },
      { value: 'Senior Dev', label: 'Strauss GmbH & Co. KG', accent: 'brand' },
      { value: 'M.Sc.', label: 'Angewandte Informatik' },
      { value: 'WayVenture', label: 'Live Founder Product', accent: 'amber' },
    ],
    code: {
      role: 'Senior Full-Stack & AI-Pragmatiker',
      badge: 'Clean Code Mode',
      credentials: [ 'M.Sc. Angewandte Informatik', 'Zero-Trust Kubernetes Research', 'Strauss Core Microservices' ],
      mantra: 'Publish early, but publish complete.',
    },
    teaserTitle: 'Gründerprojekt: WayVenture',
    teaserText: 'Smarte All-in-One Reisebegleiter App',
  },
  competencies: {
    eyebrow: 'Technologische Exzellenz',
    icon: 'verified',
    title: 'Handwerk & Kernkompetenzen',
    text: 'Kein leeres Berater-Geschwätz, sondern erprobte Ingenieursdisziplin. Nachhaltiger Code, zero-overhead Architekturen und produktionssichere Integrationen.',
    badge: 'DISZIPLINEN // 04 SÄULEN',
    stackTitle: 'Tech-Stack im Überblick',
    stackGroups: {
      frontend: 'Frontend & Mobile',
      backend: 'Backend',
      data: 'Datenbanken & Echtzeit',
      cloud: 'Cloud & DevOps',
      quality: 'Qualität & Prozesse',
      ai: 'KI & Agenten',
    },
    items: [
      {
        icon: 'devices',
        accent: 'brand',
        title: 'Moderne Web-Frontends',
        text: 'Schnelle, barrierefreie und SEO-optimierte Benutzeroberflächen mit Next.js, Nuxt, Angular und Vue.js, TypeScript und Tailwind CSS. Maximale Core Web Vitals.',
        tags: [ 'Next.js', 'Nuxt', 'Angular', 'Vue.js', 'TypeScript' ],
      },
      {
        icon: 'dns',
        accent: 'indigo',
        title: 'Backend & Cloud Microservices',
        text: 'Robuste APIs mit C# .NET, PHP (Laravel, Symfony) und Java, Domain-Driven Design (DDD) sowie Kubernetes Zero-Trust Workload-Isolation aus fundierter Master-Forschung.',
        tags: [ 'C# .NET', 'PHP / Laravel', 'Symfony', 'Java', 'K8s' ],
      },
      {
        icon: 'smart_toy',
        accent: 'emerald',
        title: 'Agentic AI & MCP Workflows',
        text: 'Moderne KI-Werkzeuge nicht als Spielerei, sondern als strukturierte Entwicklungspartner: Claude Code, Model Context Protocol (MCP) und deterministische Pipelines.',
        tags: [ 'MCP Protocol', 'Claude Code', 'Local LLM' ],
      },
      {
        icon: 'architecture',
        accent: 'amber',
        title: 'Clean Code & Qualität',
        text: 'Wartbare Software statt technischer Schulden. Automatisierte Testabdeckung (Unit, Integration, E2E), klare Schichtenarchitektur und dokumentierte Schnittstellen.',
        tags: [ 'TDD', 'CI/CD', 'Refactoring' ],
      },
    ],
  },
  wayventure: {
    badge: 'Eigenes Live-Produkt · Gründerperspektive',
    title: 'WayVenture —',
    titleHighlight: 'Der smarte Begleiter für Entdecker',
    text: 'Als leidenschaftlicher Reisender und Softwarearchitekt baue ich mit **WayVenture** das All-in-One Betriebssystem für Abenteurer, Camper und Roadtrips. Schluss mit 5 verschiedenen Apps: digitaler Reisepass, Reisebudget und KI-Reise-Timeline an einem Ort.',
    features: [
      { icon: 'badge', title: 'Digitaler Travel Pass', text: 'Bereiste Länder als Stempel im Reisepass.' },
      { icon: 'payments', title: 'Reise-Budget Planer', text: 'Ausgaben pro Reise & Wegpunkt im Blick.' },
      { icon: 'psychology', title: 'KI-Reiselinie & Zwischenstopps', text: 'Wegpunkte automatisch als Reise-Story.' },
      { icon: 'directions_car', title: 'Fahrzeug-Management', text: 'Vom Alltagsauto bis zum Wohnmobil.' },
    ],
    primaryCta: 'wayventure.de besuchen',
    secondaryCta: 'Architektur-Case anfragen',
    imageAlt: 'Oberfläche der Reisebegleiter-App WayVenture',
    status: 'Live auf wayventure.de',
  },
  motto: {
    eyebrow: '// Mein persönlicher Leitsatz',
    quote: 'Publish early, but publish complete.',
    text: 'Geschwindigkeit ist wertlos, wenn das MVP beim ersten echten Kundenkontakt zerbricht. Wir kombinieren schnelle Time-to-Market mit verlässlicher Schärfe im Detail.',
    pillars: [
      {
        badge: 'PILLAR 01',
        icon: 'rocket_launch',
        accent: 'brand',
        title: 'Publish Early',
        text: 'Nicht 9 Monate im luftleeren Raum entwickeln: Hypothesen schnell mit echten Nutzern testen, wertvolles Feedback sichern und Feature-Entscheidungen absichern.',
        points: [ 'Schnelle Prototypen-Releases', 'Echte Feedback-Schleifen von Tag 1', 'Klare MVP-Priorisierung' ],
      },
      {
        badge: 'PILLAR 02',
        icon: 'verified',
        accent: 'amber',
        title: 'Publish Complete',
        text: 'Minimal bedeutet niemals fehlerhaft. Jedes Release besitzt funktionierende Auth, saubere Error-States, stimmiges UI und durchdachte Sicherheitsstandards.',
        points: [ 'Durchdachte Edge-Case-Behandlung', 'Robuste Fehlerbehandlung & Fallbacks', 'Ausgereifte Ergonomie (Mobile & Web)' ],
      },
      {
        badge: 'FOUNDER ADVISORY',
        icon: 'lightbulb',
        accent: 'indigo',
        title: 'Interim CTO & MVP Scoping',
        text: 'Unterstützung nicht-technischer Gründer: Make-or-Buy-Entscheidungen, Tech-Stack-Auswahl und Sicherstellung, dass der Source-Code in euren Händen liegt.',
        cta: 'Gründer-Beratung anfragen',
      },
      {
        badge: 'ORGANIZATION SCALING',
        icon: 'groups',
        accent: 'emerald',
        title: 'Entwicklerteam & Prozess-Setup',
        text: 'Aufbau schlagkräftiger Teams: Etablierung sauberer Branching-Strategien, CI/CD-Pipelines, Agile Rituale und technische Interviews bei Neueinstellungen.',
        cta: 'Team-Enablement anfragen',
      },
    ],
  },
  offers: {
    eyebrow: 'Klare Pakete & Konditionen',
    icon: 'inventory_2',
    title: 'Transparente Web- & Software-Lösungen',
    text: 'Für Gründer, Mittelstand und Dienstleister: Keine unübersichtlichen Agentur-Stundensätze, sondern klare Meilensteine und messbare Ergebnisse.',
    packages: [
      {
        tier: 'Starter',
        title: 'Static One-Pager',
        text: 'Perfekt für Kampagnen, Freelancer-Portfolios oder Produkttests mit messerscharfem Fokus.',
        features: [ 'Extrem schnelle Ladezeiten (<1s)', '100% DSGVO-konform ohne Cookies', 'Mobile-First Ergonomie', 'Lead- / Kontaktformular' ],
      },
      {
        tier: 'Dynamisch',
        title: 'Interactive CMS Page',
        text: 'Für wachsende Betriebe, die Inhalte, Referenzen und News selbstständig pflegen möchten.',
        features: [ 'Schlankes Headless CMS', 'Texte & Bilder ohne Code anpassen', 'Interaktive Filter & Animationen', 'Domain-, SSL- & Mail-Einrichtung' ],
        featured: true,
      },
      {
        tier: 'Wachstum',
        title: 'Business Website',
        text: 'Umfassender digitaler Auftritt mit mehreren Leistungsseiten und Suchmaschinen-Strategie.',
        features: [ 'Bis zu 5 individuelle Unterseiten', 'SEO Schema Markup & Metadaten', 'Individuelles UI/UX Konzept', 'Redaktions-Workflow & Rollen' ],
      },
      {
        tier: 'Full-Scale',
        title: 'Enterprise System',
        text: 'Individuelle Portale, Kundenbereiche oder Schnittstellenanbindungen mit höchster Sicherheit.',
        features: [ 'Komplexe Rollen & Auth (OAuth)', 'API- & Drittsystem-Anbindung', '99+ Lighthouse Performance Score', 'Dedicated Support & SLA' ],
      },
    ],
    requestCta: 'Paket anfragen',
    featuredCta: 'Paket auswählen',
    featuredBadge: 'Empfehlung',
    custom: {
      title: 'Individuelle Softwarearchitektur oder MVP-Entwicklung gesucht?',
      text: 'Benötigen Sie skalierbare C# .NET Microservices, mobile Hybrid-Apps oder eine fundierte Zero-Trust Cloud-Infrastruktur? Lassen Sie uns die Anforderungen besprechen.',
      cta: 'Architektur-Gespräch buchen',
    },
  },
  aiConsulting: {
    eyebrow: 'Kein Hype, sondern Handwerk',
    icon: 'psychology',
    title: 'AI Consulting & Entwickler-Coaching',
    text: 'Die meisten KI-Workshops enden bei oberflächlichen ChatGPT-Prompts. Ich zeige Teams, wie autonome Agenten und deterministische Schnittstellen echten Code erzeugen, ohne Kontrollverlust.',
    tracks: [
      {
        badge: 'FÜR UNTERNEHMEN & TEAMS',
        icon: 'apartment',
        accent: 'brand',
        title: 'Agenten-Workflow Migration & KI-Audit',
        text: 'Wir analysieren bestehende Entwicklungszyklen und integrieren KI-Agenten sicher in die Toolchain – unter strenger Beachtung von DSGVO, IP-Schutz und Code-Qualitätsmetriken.',
        items: [
          { icon: 'query_stats', title: 'Engineering Bottleneck Audit', text: 'Wo Agenten wirklich Entwicklerzeit sparen (und wo sie schaden).' },
          { icon: 'policy', title: 'Governance & Datenschutz-Compliance', text: 'Klare Leitlinien für Ollama, Claude Enterprise und OpenAI.' },
          { icon: 'speed', title: 'Hands-on MVP Deployment', text: 'Konkrete Pilot-Integration innerhalb weniger Tage statt Monaten.' },
        ],
        cta: 'Strategie-Gespräch vereinbaren',
      },
      {
        badge: 'ENTWICKLER ZU ENTWICKLER',
        icon: 'terminal',
        accent: 'emerald',
        title: 'Mastering AI Agents: 1:1 Coaching',
        text: 'Lernen Sie, wie Sie Claude Code, Terminal-Agenten und MCP-Server einsetzen, um 5-mal schneller zu liefern, während Sie 100% der architektonischen Kontrolle behalten.',
        items: [
          { icon: 'code', title: 'Claude Code & CLI Agenten', text: 'Kontextfenster strukturieren, Sub-Tasking und Branch-Hygiene.' },
          { icon: 'hub', title: 'Eigene MCP-Server programmieren', text: 'Eigene Datenbanken & APIs direkt an LLM-Agenten anbinden.' },
          { icon: 'check_circle', title: 'TDD als Agenten-Leitplanke', text: 'Automatisierte Tests als Qualitätsfilter für KI-generierte Commits.' },
        ],
        cta: '1:1 Coaching anfragen',
      },
    ],
  },
  experience: {
    eyebrow: 'Erfahrung & Stationen',
    icon: 'history_edu',
    title: 'Beruflicher Werdegang',
    text: 'Solide Industrieerfahrung, wissenschaftliche Tiefe in verteilten Systemen und eigenverantwortliche Produktentwicklung.',
    items: [
      {
        title: 'Freelance Senior Developer & AI-Ambassador',
        period: 'Seit Juni 2026',
        text: 'Entwicklung von skalierbaren Next.js-Websystemen und API-Backends. Für eine Agentur mit Fokus auf KI-Entwicklung bringe ich Prinzipien klassischer Softwareentwicklung in agentische Workflows und MCP-Server.',
        accent: 'brand',
      },
      {
        title: 'Gründer & Lead Architect — WayVenture',
        period: 'Seit April 2026',
        text: 'Aufbau und Betrieb der mobilen All-in-One Reisebegleiter-App mit digitalem Reisepass, Reisebudget, KI-Reise-Timeline und Fahrzeugverwaltung.',
        accent: 'amber',
      },
      {
        title: 'Full Stack Developer — Strauss GmbH & Co. KG',
        period: 'Seit Okt. 2024',
        text: 'Entwicklung und Betreuung von Core Microservices mit C# .NET und Angular, die schrittweise die Funktionen eines Legacy-Systems ablösen.',
        accent: 'indigo',
      },
      {
        title: 'Freelance Lead Dev: JagdTausch Marktplatz MVP',
        period: 'Juli 2024 – Sept. 2025',
        text: 'Konzeption und schlüsselfertige Realisierung der Marktplatz-Plattform (PWA) für gebrauchte Jagdausrüstung inklusive Echtzeit-Chat, Filtersystem und Admin-Dashboard.',
        accent: 'slate',
      },
      {
        title: 'Working Student Full Stack — Reservix',
        period: 'Dez. 2021 – Sept. 2024',
        text: 'Entwicklung eines Reporting-Tools für Theater und Veranstalter, mit dem Auswertungen von Ticketverkäufen deutlich einfacher werden. PHP, TypeScript, MongoDB, Terraform und Mercure.',
        accent: 'slate',
      },
      {
        title: 'Werkstudent & Bachelorand — ECOPLAN GmbH',
        period: 'Sept. 2017 – Sept. 2021',
        text: 'Aufbau und kundenspezifische Anpassung eines CRM-Systems für mehrere Kunden, inklusive Integration der Schweizer QR-Rechnung. Webservices mit Java EE auf Tomcat.',
        accent: 'slate',
      },
    ],
    highlights: [
      {
        icon: 'school',
        eyebrow: 'M.Sc. Angewandte Informatik',
        meta: '• Hochschule Fulda',
        title: 'Masterarbeit: Kubernetes Security & Zero Trust Architecture',
        text: 'Forschung zur Absicherung von Container-Infrastrukturen, Workload-Isolation, Service Meshes (mTLS mit Istio) und automatisierten Runtime-Sicherheitsanalysen.',
        href: '/Masterthesis.pdf',
      },
    ],
  },
  volunteering: {
    badge: 'Gesellschaftliche Verantwortung & Werte',
    title: 'Freiwillige Feuerwehr — Einsatz & Verlässlichkeit unter Druck',
    text: 'Verantwortung endet für mich nicht am Bildschirm. Seit 2018 bin ich aktiver Truppführer in der Freiwilligen Feuerwehr (Feuerwehr Fulda-Mitte 2018–2024, Feuerwehr Hofbieber-Mitte seit 2024).',
    values: [
      { label: 'Fokus', value: 'Teamgeist' },
      { label: 'Bereitschaft', value: '24/7 Verlässlichkeit' },
      { label: 'Führung', value: 'Klare Kommunikation' },
      { label: 'Krisenfest', value: 'Ruhe unter Last' },
    ],
    quoteLabel: '// Transfer ins Engineering',
    quote: 'Im Einsatz wie bei kritischen Produktionsausfällen: Klare Prioritäten, blindes Vertrauen ins Team und entschlossenes Handeln ohne Panik führen zum Erfolg.',
    signature: 'Christian Dechant, Truppführer',
  },
  contact: {
    testimonials: [
      {
        name: 'Caroline Grabowski',
        role: 'JagdTausch',
        text: 'Tolle Zusammenarbeit – immer zuverlässig, pünktlich und mit Leidenschaft bei der Sache. Er hat sich für alles Zeit genommen und einen fantastischen Job gemacht!',
      },
      {
        name: 'Studierendenvertretung Sensorik, Aktorik & Elektronik',
        role: 'Technische Universität Darmstadt',
        text: 'Kompetente Beratung und zuverlässige Umsetzung kundenspezifischer Anforderungen!',
        initials: 'TU',
      },
    ],
    eyebrow: 'Direkter Kontakt',
    title: 'Lassen Sie uns Ihr Projekt besprechen',
    text: 'Ob Senior Freelance-Kapazität für Ihr Web- & Cloud-Projekt, maßgeschneiderte KI-Workflows oder technisches Sparring: Ich melde mich innerhalb von 24 Stunden persönlich zurück.',
    items: [
      { label: 'E-MAIL', text: contactEmail, href: `mailto:${ contactEmail }`, icon: 'send', accent: 'brand' },
      { label: 'STANDORT', text: 'Hofbieber / Hessen (Remote-First)', icon: 'location_on', accent: 'brand' },
      { label: 'ANTWORTGARANTIE', text: '< 24h Reaktionszeit', icon: 'schedule', accent: 'emerald' },
    ],
    form: {
      name: 'Ihr Name *',
      namePlaceholder: 'z.B. Anna Schmidt',
      email: 'E-Mail Adresse *',
      emailPlaceholder: 'anna@unternehmen.de',
      scope: 'Projektbereich',
      scopes: [
        { value: 'freelance', label: 'Freelance Web / Full-Stack (Next.js, C# .NET)' },
        { value: 'ai', label: 'AI Consulting / Agentic Workflows / MCP' },
        { value: 'package', label: 'Webseiten-Paket (One-Pager, CMS, Business)' },
        { value: 'coaching', label: '1:1 Entwickler-Coaching' },
        { value: 'founder', label: 'Gründer-Beratung / Team-Setup' },
        { value: 'wayventure', label: 'WayVenture Kooperation' },
      ],
      message: 'Kurzbeschreibung & Ziele *',
      messagePlaceholder: 'Worum geht es in Ihrem Projekt? Welcher Zeitrahmen ist angedacht?',
      consent: [
        'Ich stimme zu, dass meine Angaben zur Kontaktaufnahme und Beantwortung meiner Anfrage verarbeitet werden (',
        'Datenschutzerklärung',
        ').',
      ],
      submit: 'Anfrage absenden',
      sending: 'Wird gesendet …',
      success: 'Vielen Dank! Ihre Nachricht wurde übermittelt. Christian Dechant meldet sich zeitnah bei Ihnen.',
      rateLimited: 'Zu viele Anfragen in kurzer Zeit. Bitte versuchen Sie es in ein paar Minuten erneut oder schreiben Sie direkt eine E-Mail.',
      error: 'Leider ist etwas schiefgelaufen. Bitte versuchen Sie es erneut oder schreiben Sie direkt eine E-Mail.',
    },
  },
  cookieBanner: {
    eyebrow: 'Cookies & Datenschutz',
    title: 'Ihre Privatsphäre zählt',
    text: [
      'Diese Website nutzt nur technisch notwendige Speicherung, z.B. um Ihre Auswahl hier zu merken. Optionale Dienste werden nur mit Ihrer Einwilligung geladen, die Sie jederzeit im Seitenfuß widerrufen können. Mehr in der ',
      'Datenschutzerklärung',
      '.',
    ],
    acceptAll: 'Alle akzeptieren',
    necessaryOnly: 'Nur notwendige',
    settings: 'Einstellungen',
    save: 'Auswahl speichern',
    alwaysActive: 'Immer aktiv',
    categories: {
      necessary: {
        title: 'Notwendig',
        text: 'Speichert Ihre Cookie-Auswahl lokal in Ihrem Browser. Ohne diese Speicherung funktioniert der Banner nicht.',
      },
      statistics: {
        title: 'Statistik & externe Medien',
        text: 'Derzeit sind keine solchen Dienste eingebunden. Neue Dienste werden erst nach Ihrer Zustimmung geladen.',
      },
    },
  },
  footer: {
    tagline: 'InterestedOWL · M.Sc. Angewandte Informatik · Senior Full-Stack & Applied AI',
    imprint: 'Impressum',
    privacy: 'Datenschutz',
    languageLabel: 'Sprache wählen',
    cookieSettings: 'Cookie-Einstellungen',
    rights: 'Alle Rechte vorbehalten.',
    status: 'Bereit für ausgewählte Neuprojekte',
  },
  wayventurePage: {
    metaTitle: 'WayVenture — Reiseplaner-App von Christian Dechant',
    metaDescription: 'WayVenture ist eine unabhängige Reiseplaner-App für Roadtrips, Camper-Reisen und spontane Kurztrips – mit digitalem Reisepass, KI-Reise-Timeline, Budgetplanung und Fahrzeugverwaltung. Entwickelt von Christian Dechant.',
    back: 'Zurück zur Startseite',
    badge: 'Gründerprojekt · Live-Produkt',
    title: 'WayVenture',
    subtitle: 'Dein smarter Reiseplaner – von der Planung bis zur Erinnerung.',
    intro: 'WayVenture ist eine Mobile-First Reiseplaner-App, die ich unabhängig neben meiner Freelance-Tätigkeit konzipiert und entwickelt habe. Sie hilft Reisenden, schnell loszukommen und ohne Vorbereitungsaufwand organisiert zu bleiben – egal ob spontaner Wochenend-Roadtrip oder durchgeplante Camper-Reise durch mehrere Länder.',
    tryCta: 'WayVenture kostenlos testen',
    storyTitle: 'Warum ich WayVenture gebaut habe',
    story: [
      'Die meisten Reise-Apps gehen davon aus, dass eine Reise Wochen im Voraus geplant wird. In der Praxis beginnen viele der besten Reisen fast ohne Planung: ein freies Wochenende, ein voller Tank und eine grobe Richtung. WayVenture behandelt spontane und geplante Reisen gleichwertig: Eine spontane Reise ist in einem Schritt angelegt – Name, Startdatum, Budget und Status werden automatisch gesetzt –, während eine geplante Reise eine vollständige Route mit Wegpunkten und länderspezifischen Reisehinweisen erhält.',
      'Das Produkt folgt ein paar einfachen Prinzipien: Mobile-First, schneller Zugriff auf relevante Informationen, möglichst wenig Vorbereitungsaufwand, offline-freundlich wo möglich und inkrementelle Releases statt eines großen Launches. Darunter steckt ein sauber entwickelter Stack: ein Next.js- und TypeScript-Frontend, ein Django-REST-Framework-Backend, Stripe für Abonnements und ein containerisiertes Docker-Deployment mit Fokus auf Sicherheit und Skalierbarkeit von Tag eins an.',
    ],
    featuresTitle: 'Was WayVenture kann',
    featuresText: 'Eine All-in-One Reise-App: Reise planen, erleben und die Erinnerung bewahren.',
    features: [
      { icon: 'badge', title: 'Digitaler Reisepass', description: 'Jedes bereiste Land wird im digitalen Reisepass abgestempelt – so wird deine Reisehistorie zu etwas, auf das du wirklich zurückblicken kannst.', badge: 'USP' },
      { icon: 'payments', title: 'Reise-Budget Planer', description: 'Ausgaben pro Reise und pro Wegpunkt erfassen, damit du schon vorher weißt, was ein spontaner Umweg kostet.' },
      { icon: 'map', title: 'Wegpunkte & Reisehinweise', description: 'Wegpunkte spontan hinzufügen, länderspezifische Reisehinweise erhalten und Routen per Link mit Mitreisenden teilen.' },
      { icon: 'auto_awesome', title: 'KI-Reise-Timeline', description: 'Eine KI-generierte Zusammenfassung macht aus Wegpunkten und Daten automatisch eine lesbare Geschichte deiner Reise.', badge: 'KI' },
      { icon: 'group', title: 'Teilen & Einladen', description: 'Reisen per Freigabe- oder Einladungslink teilen, damit Freunde und Familie auch ohne Konto mitverfolgen können.' },
      { icon: 'directions_car', title: 'Fahrzeug-Management', description: 'Fahrzeuge – vom Alltagsauto bis zum Wohnmobil – direkt den passenden Reisen zuordnen.' },
    ],
    screenshotAlt: 'Screenshot der WayVenture Reise-App mit Reiseplanung, digitalem Reisepass und Budgetübersicht',
    roadmapTitle: 'Was als Nächstes kommt',
    roadmapText: 'WayVenture wird inkrementell ausgeliefert. Das steht auf der Roadmap:',
    upcoming: [
      { icon: 'favorite', title: 'Community-Funktionen' },
      { icon: 'dashboard_customize', title: 'Creator-Modus' },
      { icon: 'checklist', title: 'Ausrüstungs-Checklisten' },
      { icon: 'camping', title: 'Stellplätze' },
      { icon: 'smart_toy', title: 'KI-Reiseagent' },
      { icon: 'photo_album', title: 'Reise-Fotobuch' },
    ],
    vaultTitle: 'Document Safe',
    vaultSubtitle: '(Digitaler Tresor)',
    vaultText: 'Ein geplantes Alleinstellungsmerkmal: ein sicherer, verschlüsselter Ort für Reise- und Fahrzeugdokumente mit Offline-Verfügbarkeit, Ablauf-Erinnerungen, Reise-Checklisten und OCR – damit Reisepass, Visa und Fahrzeugpapiere auch ohne Verbindung nur einen Tipp entfernt sind.',
    faqTitle: 'Häufige Fragen',
    faq: [
      {
        question: 'Was ist WayVenture?',
        answer: 'WayVenture ist eine Mobile-First Reisebegleiter-App zum Planen und Erleben von Roadtrips und spontanen Kurztrips. Sie kombiniert digitalen Reisepass, Budgetplanung, KI-generierte Reise-Timelines, wegpunktbasierte Reisehinweise und Fahrzeugverwaltung in einer All-in-One-App.',
      },
      {
        question: 'Wer hat WayVenture entwickelt?',
        answer: 'WayVenture ist ein unabhängiges Produkt, das Christian Dechant als Full-Stack-Entwickler neben seiner Freelance-Tätigkeit konzipiert und entwickelt hat.',
      },
      {
        question: 'Was unterscheidet WayVenture von anderen Reiseplanern?',
        answer: 'WayVenture behandelt geplante und spontane Reisen gleichwertig. Eine spontane Reise ist in einem Schritt angelegt – Name, Startdatum und Budget werden automatisch ausgefüllt –, während geplante Reisen eine vollständige Route mit Wegpunkten und länderspezifischen Reisehinweisen erhalten.',
      },
      {
        question: 'Ist WayVenture kostenlos?',
        answer: 'WayVenture bietet einen kostenlosen Tarif sowie die kostenpflichtigen Tarife Weltenbummler und Globetrotter, die z.B. Reisehinweise pro Wegpunkt und höhere Nutzungslimits freischalten.',
      },
      {
        question: 'Was kommt als Nächstes?',
        answer: 'Auf der Roadmap stehen Community-Funktionen, ein Creator-Modus, Ausrüstungs-Checklisten, Stellplatzsuche, ein KI-Reiseagent, ein Reise-Fotobuch und ein „Document Safe“ zur sicheren Ablage von Reise- und Fahrzeugdokumenten mit OCR und Ablauf-Erinnerungen.',
      },
      {
        question: 'Wo kann ich WayVenture ausprobieren?',
        answer: 'WayVenture ist live auf wayventure.de – auf Deutsch und Englisch, ohne Kreditkarte für den Start.',
      },
    ],
    visitCta: 'WayVenture besuchen',
    talkCta: 'Lass uns darüber sprechen',
  },
  notFound: {
    title: 'Seite nicht gefunden',
    text: 'Die angeforderte Seite existiert nicht (mehr). Vielleicht hilft ein Blick auf die Startseite.',
    cta: 'Zur Startseite',
  },
  imprint: {
    metaTitle: 'Impressum | Christian Dechant',
    metaDescription: 'Impressum und Anbieterkennzeichnung von Christian Dechant gemäß § 5 DDG.',
    eyebrow: 'Rechtliches',
    title: 'Impressum',
    updated: legalUpdated,
    sections: [
      {
        heading: 'Angaben gemäß § 5 DDG',
        paragraphs: [ 'Christian Dechant\nLangenbieberer Str. 14\n36145 Hofbieber\nDeutschland' ],
      },
      {
        heading: 'Kontakt',
        paragraphs: [ `E-Mail: ${ contactEmail }` ],
      },
      {
        heading: 'Umsatzsteuer',
        paragraphs: [ 'Kleinunternehmer im Sinne von § 19 UStG. Es wird keine Umsatzsteuer berechnet und ausgewiesen.' ],
      },
      {
        heading: 'Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV',
        paragraphs: [ 'Christian Dechant\nLangenbieberer Str. 14\n36145 Hofbieber' ],
      },
      {
        heading: 'Verbraucherstreitbeilegung',
        paragraphs: [ 'Ich bin nicht bereit und nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.' ],
      },
      {
        heading: 'Haftung für Inhalte',
        paragraphs: [
          'Die Inhalte dieser Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann ich jedoch keine Gewähr übernehmen. Als Diensteanbieter bin ich gemäß § 7 Abs. 1 DDG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich.',
          'Nach §§ 8 bis 10 DDG bin ich als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden entsprechender Rechtsverletzungen werde ich diese Inhalte umgehend entfernen.',
        ],
      },
      {
        heading: 'Haftung für Links',
        paragraphs: [
          'Dieses Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte ich keinen Einfluss habe. Deshalb kann ich für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.',
          'Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werde ich derartige Links umgehend entfernen.',
        ],
      },
      {
        heading: 'Urheberrecht',
        paragraphs: [
          'Die durch den Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.',
          'Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitte ich um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werde ich derartige Inhalte umgehend entfernen.',
        ],
      },
    ],
  },
  privacy: {
    metaTitle: 'Datenschutzerklärung | Christian Dechant',
    metaDescription: 'Informationen zur Verarbeitung personenbezogener Daten auf christiandechant.de gemäß DSGVO.',
    eyebrow: 'Rechtliches',
    title: 'Datenschutzerklärung',
    intro: 'Der Schutz Ihrer personenbezogenen Daten ist mir wichtig. Nachfolgend informiere ich Sie gemäß Art. 13 DSGVO darüber, welche Daten beim Besuch dieser Website verarbeitet werden, zu welchem Zweck und auf welcher Rechtsgrundlage.',
    updated: legalUpdated,
    sections: [
      {
        heading: '1. Verantwortlicher',
        paragraphs: [
          'Verantwortlich für die Datenverarbeitung auf dieser Website im Sinne der Datenschutz-Grundverordnung (DSGVO) ist:',
          `Christian Dechant\nLangenbieberer Str. 14\n36145 Hofbieber\nDeutschland\nE-Mail: ${ contactEmail }`,
          'Ein Datenschutzbeauftragter ist nicht benannt, da hierzu keine gesetzliche Pflicht besteht.',
        ],
      },
      {
        heading: '2. Rechtsgrundlagen',
        paragraphs: [ 'Ich verarbeite personenbezogene Daten auf Grundlage der folgenden Rechtsgrundlagen:' ],
        list: [
          'Art. 6 Abs. 1 lit. a DSGVO – Einwilligung',
          'Art. 6 Abs. 1 lit. b DSGVO – Vertragserfüllung und vorvertragliche Maßnahmen',
          'Art. 6 Abs. 1 lit. c DSGVO – Erfüllung einer rechtlichen Verpflichtung',
          'Art. 6 Abs. 1 lit. f DSGVO – berechtigte Interessen',
          '§ 25 Abs. 1 und 2 TDDDG – Speicherung von und Zugriff auf Informationen in Ihrem Endgerät',
        ],
      },
      {
        heading: '3. Hosting',
        paragraphs: [
          'Diese Website wird bei der Hetzner Online GmbH, Industriestr. 25, 91710 Gunzenhausen, Deutschland, gehostet. Beim Aufruf der Website werden die unten genannten Server-Logfiles auf den Servern des Hosters verarbeitet.',
          'Die Nutzung des Hosters erfolgt im Interesse einer sicheren, schnellen und effizienten Bereitstellung dieser Website (Art. 6 Abs. 1 lit. f DSGVO). Mit dem Hoster besteht ein Vertrag über Auftragsverarbeitung gemäß Art. 28 DSGVO.',
        ],
      },
      {
        heading: '4. Server-Logfiles',
        paragraphs: [ 'Bei jedem Aufruf dieser Website erfasst der Webserver automatisch Informationen, die Ihr Browser übermittelt:' ],
        list: [
          'IP-Adresse des anfragenden Geräts',
          'Datum und Uhrzeit des Zugriffs',
          'aufgerufene Seite bzw. Datei und HTTP-Statuscode',
          'übertragene Datenmenge',
          'Referrer-URL (zuvor besuchte Seite)',
          'Browsertyp, Browserversion und Betriebssystem (User Agent)',
        ],
        subsections: [
          {
            heading: 'Zweck, Rechtsgrundlage und Speicherdauer',
            paragraphs: [
              'Die Verarbeitung ist erforderlich, um die Website auszuliefern, ihre Stabilität und Sicherheit zu gewährleisten und Missbrauch abzuwehren. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Eine Zusammenführung mit anderen Datenquellen findet nicht statt. Die Logfiles werden gelöscht, sobald sie für diese Zwecke nicht mehr erforderlich sind.',
            ],
          },
        ],
      },
      {
        heading: '5. Kontaktformular und E-Mail',
        paragraphs: [
          'Wenn Sie mir über das Kontaktformular oder per E-Mail eine Anfrage senden, verarbeite ich die von Ihnen angegebenen Daten (Name, E-Mail-Adresse, gewählter Projektbereich und Ihre Nachricht), um Ihre Anfrage zu bearbeiten und Ihnen zu antworten. Nach dem Absenden erhalten Sie an die angegebene E-Mail-Adresse eine automatische Eingangsbestätigung mit einer Kopie Ihrer Angaben.',
          'Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, sofern Ihre Anfrage mit der Anbahnung oder Durchführung eines Vertrags zusammenhängt, und im Übrigen Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der Beantwortung von Anfragen).',
          'Der Versand der E-Mails erfolgt über den SMTP-Server meines E-Mail-Anbieters, der die Daten als Auftragsverarbeiter verarbeitet. Eine sonstige Weitergabe an Dritte findet nicht statt.',
          'Ihre Daten werden gelöscht, sobald Ihre Anfrage abschließend bearbeitet ist und keine gesetzlichen Aufbewahrungspflichten (z.B. für Geschäftsbriefe nach § 257 HGB bzw. § 147 AO) entgegenstehen.',
        ],
      },
      {
        heading: '6. Cookies und Einwilligungsverwaltung',
        paragraphs: [
          'Diese Website setzt keine Tracking- oder Werbe-Cookies ein und bindet derzeit keine optionalen Dienste Dritter ein. Beim ersten Besuch fragt ein Banner nach Ihrer Einwilligung für optionale Dienste, damit neue Dienste erst nach Ihrer Zustimmung geladen werden.',
          'Ihre Auswahl (erteilte Kategorien, Version und Zeitpunkt) wird ausschließlich lokal im Speicher Ihres Browsers (localStorage, Schlüssel „cd-consent“) abgelegt und nicht an meinen Server oder Dritte übertragen. Nach 12 Monaten werden Sie erneut gefragt.',
          'Die Speicherung ist unbedingt erforderlich, um Ihre Entscheidung zu berücksichtigen (§ 25 Abs. 2 Nr. 2 TDDDG); Rechtsgrundlage für die Verarbeitung ist Art. 6 Abs. 1 lit. c DSGVO i.V.m. Art. 7 Abs. 1 DSGVO. Sie können Ihre Auswahl jederzeit über den Link „Cookie-Einstellungen“ im Seitenfuß ändern oder widerrufen oder sie durch Löschen der Websitedaten in Ihrem Browser entfernen.',
        ],
      },
      {
        heading: '7. Schriftarten und Icons',
        paragraphs: [
          'Die auf dieser Website verwendeten Schriftarten (Geist, JetBrains Mono) und Icons (Material Symbols) werden lokal von meinem eigenen Server ausgeliefert. Es wird keine Verbindung zu Servern von Google oder anderen Drittanbietern aufgebaut.',
        ],
      },
      {
        heading: '8. Links zu externen Websites und sozialen Netzwerken',
        paragraphs: [
          'Diese Website enthält einfache Links zu externen Angeboten, z.B. LinkedIn, XING, GitHub, wayventure.de und jagdtausch.de. Es handelt sich nicht um eingebundene Plugins: Beim bloßen Besuch dieser Website werden keine Daten an diese Anbieter übertragen. Erst wenn Sie einen Link anklicken, gelangen Sie auf die Website des jeweiligen Anbieters, für die dessen Datenschutzbestimmungen gelten.',
        ],
      },
      {
        heading: '9. SSL- bzw. TLS-Verschlüsselung',
        paragraphs: [
          'Diese Website nutzt aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, wie z.B. Anfragen über das Kontaktformular, eine TLS-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie an „https://“ in der Adresszeile Ihres Browsers.',
        ],
      },
      {
        heading: '10. Ihre Rechte',
        paragraphs: [ 'Ihnen stehen hinsichtlich Ihrer personenbezogenen Daten folgende Rechte zu:' ],
        list: [
          'Auskunft über die verarbeiteten Daten (Art. 15 DSGVO)',
          'Berichtigung unrichtiger Daten (Art. 16 DSGVO)',
          'Löschung Ihrer Daten (Art. 17 DSGVO)',
          'Einschränkung der Verarbeitung (Art. 18 DSGVO)',
          'Datenübertragbarkeit (Art. 20 DSGVO)',
          'Widerruf einer erteilten Einwilligung mit Wirkung für die Zukunft (Art. 7 Abs. 3 DSGVO)',
        ],
        subsections: [
          {
            heading: 'Widerspruchsrecht (Art. 21 DSGVO)',
            paragraphs: [
              'Soweit ich Ihre Daten auf Grundlage berechtigter Interessen (Art. 6 Abs. 1 lit. f DSGVO) verarbeite, haben Sie das Recht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit Widerspruch gegen diese Verarbeitung einzulegen.',
            ],
          },
          {
            heading: 'Beschwerderecht bei einer Aufsichtsbehörde',
            paragraphs: [
              'Sie haben das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren (Art. 77 DSGVO). Zuständig ist: Der Hessische Beauftragte für Datenschutz und Informationsfreiheit, Gustav-Stresemann-Ring 1, 65189 Wiesbaden, https://datenschutz.hessen.de',
            ],
          },
          {
            heading: 'Geltendmachung',
            paragraphs: [ `Zur Ausübung Ihrer Rechte genügt eine formlose Nachricht an ${ contactEmail }.` ],
          },
        ],
      },
      {
        heading: '11. Pflicht zur Bereitstellung und automatisierte Entscheidungen',
        paragraphs: [
          'Sie sind weder gesetzlich noch vertraglich verpflichtet, mir personenbezogene Daten bereitzustellen. Ohne Name und E-Mail-Adresse kann ich eine Anfrage über das Kontaktformular jedoch nicht beantworten. Eine automatisierte Entscheidungsfindung einschließlich Profiling (Art. 22 DSGVO) findet nicht statt.',
        ],
      },
      {
        heading: '12. Änderungen dieser Datenschutzerklärung',
        paragraphs: [
          'Ich passe diese Datenschutzerklärung an, sobald Änderungen der Website oder der Rechtslage dies erforderlich machen. Es gilt die jeweils hier veröffentlichte Fassung.',
        ],
      },
    ],
  },
};
