import { SiteContent } from "../interfaces";
import { contactEmail } from "./shared";

const legalUpdated = 'Last updated: September 2026';

export const en: SiteContent = {
  meta: {
    title: 'Christian Dechant | Freelance Full-Stack Developer & AI Consultant',
    description: 'Freelance full-stack developer (M.Sc., 9+ years) from Germany: websites, web apps & software with Next.js, C# .NET & Laravel, plus AI consulting. Remote across Europe.',
    ogLocale: 'en_US',
    siteName: 'Christian Dechant',
    keywords: [
      'Christian Dechant',
      'freelance developer Germany',
      'freelance full-stack developer',
      'web developer',
      'app developer',
      'Next.js developer',
      'Nuxt developer',
      'Laravel developer',
      'C# .NET developer',
      'software freelancer Germany',
      'AI consulting',
      'AI strategy consultant',
      'AI agent development',
      'AI coaching for developers',
      'interim CTO',
    ],
    jobTitle: 'Senior Full-Stack & Applied AI Engineer',
    summary: 'Christian Dechant is a freelance senior full-stack developer and AI consultant based in Hofbieber near Fulda, Germany. He holds an M.Sc. in Applied Computer Science from Fulda University of Applied Sciences and has more than 9 years of software development experience. He builds websites, web apps and custom software with Next.js, Nuxt, Angular, C# .NET and PHP/Laravel, advises companies on introducing AI agents into software development, coaches developers in working with Claude Code and MCP, and is the founder of the travel app WayVenture. He works remotely for clients across Germany, Austria, Switzerland and internationally, in German and English.',
    ogTagline: 'Freelance Full-Stack Developer & AI Consultant · Germany',
    areaServed: [ 'Germany', 'Austria', 'Switzerland', 'Europe' ],
  },
  header: {
    tagline: 'Full-Stack & Applied AI',
    badge: 'Senior Dev',
    nav: [
      { href: '#about', title: 'About', mobileTitle: 'About me' },
      { href: '#wayventure', title: 'WayVenture', mobileTitle: 'WayVenture (App)', highlight: 'amber', badge: 'Live' },
      { href: '#services', title: 'Offers', mobileTitle: 'Offers & Web Packages' },
      { href: '#ai-consulting', title: 'AI Consulting', mobileTitle: 'AI Consulting & Coaching' },
      { href: '#experience', title: 'Experience', mobileTitle: 'Experience & Career' },
      { href: '#feuerwehr', title: 'Volunteering', mobileTitle: 'Volunteer Fire Department', highlight: 'rose' },
      { href: '#contact', title: 'Contact', mobileTitle: 'Contact' },
    ],
    cta: 'Start a project',
    mobileCta: 'Start a project',
    drawerTitle: 'Navigation',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    languageLabel: 'Choose language',
  },
  hero: {
    status: 'Available for selected projects & AI engineering',
    headline: 'Senior Engineering & Pragmatic AI —',
    headlineHighlight: 'built for real impact.',
    intro: 'Hi, I’m **Christian Dechant**, M.Sc. Applied Computer Science. As a Senior Full-Stack Developer at *Strauss GmbH & Co. KG* and founder of *WayVenture*, I combine 9+ years of industrial software architecture (C#, Next.js, Cloud) with deterministic, agent-driven AI development.',
    primaryCta: 'Start a project',
    secondaryCta: 'Discover WayVenture',
    imageAlt: 'Tidy developer workspace with three monitors showing code, an architecture diagram and a terminal',
    stats: [
      { value: '9+ years', label: 'Software Engineering' },
      { value: 'Senior Dev', label: 'Strauss GmbH & Co. KG', accent: 'brand' },
      { value: 'M.Sc.', label: 'Applied Computer Science' },
      { value: 'WayVenture', label: 'Live Founder Product', accent: 'amber' },
    ],
    code: {
      role: 'Senior Full-Stack & AI Pragmatist',
      badge: 'Clean Code Mode',
      credentials: [ 'M.Sc. Applied Computer Science', 'Zero-Trust Kubernetes Research', 'Strauss Core Microservices' ],
      mantra: 'Publish early, but publish complete.',
    },
    teaserTitle: 'Founder project: WayVenture',
    teaserText: 'Smart all-in-one travel companion app',
  },
  competencies: {
    eyebrow: 'Technical excellence',
    icon: 'verified',
    title: 'Craft & Core Competencies',
    text: 'No empty consultant talk, but proven engineering discipline. Sustainable code, zero-overhead architectures and production-ready integrations.',
    badge: 'DISCIPLINES // 04 PILLARS',
    stackTitle: 'Tech stack at a glance',
    stackGroups: {
      frontend: 'Frontend & mobile',
      backend: 'Backend',
      data: 'Databases & real-time',
      cloud: 'Cloud & DevOps',
      quality: 'Quality & process',
      ai: 'AI & agents',
    },
    items: [
      {
        icon: 'devices',
        accent: 'brand',
        title: 'Modern Web Frontends',
        text: 'Fast, accessible and SEO-optimized user interfaces with Next.js, Nuxt, Angular and Vue.js, TypeScript and Tailwind CSS. Maximum Core Web Vitals.',
        tags: [ 'Next.js', 'Nuxt', 'Angular', 'Vue.js', 'TypeScript' ],
      },
      {
        icon: 'dns',
        accent: 'indigo',
        title: 'Backend & Cloud Microservices',
        text: 'Robust APIs with C# .NET, PHP (Laravel, Symfony) and Java, Domain-Driven Design (DDD) and Kubernetes zero-trust workload isolation backed by in-depth master’s research.',
        tags: [ 'C# .NET', 'PHP / Laravel', 'Symfony', 'Java', 'K8s' ],
      },
      {
        icon: 'smart_toy',
        accent: 'emerald',
        title: 'Agentic AI & MCP Workflows',
        text: 'Modern AI tools not as a gimmick, but as structured development partners: Claude Code, Model Context Protocol (MCP) and deterministic pipelines.',
        tags: [ 'MCP Protocol', 'Claude Code', 'Local LLM' ],
      },
      {
        icon: 'architecture',
        accent: 'amber',
        title: 'Clean Code & Quality',
        text: 'Maintainable software instead of technical debt. Automated test coverage (unit, integration, E2E), a clear layered architecture and documented interfaces.',
        tags: [ 'TDD', 'CI/CD', 'Refactoring' ],
      },
    ],
  },
  wayventure: {
    badge: 'Own live product · Founder perspective',
    title: 'WayVenture —',
    titleHighlight: 'The smart companion for explorers',
    text: 'As a passionate traveler and software architect, I’m building **WayVenture**, the all-in-one operating system for adventurers, campers and road trips. No more juggling five different apps: digital travel pass, trip budget and AI trip timeline in one place.',
    features: [
      { icon: 'badge', title: 'Digital Travel Pass', text: 'Every country stamped into your passport.' },
      { icon: 'payments', title: 'Trip Budget Planner', text: 'Spending per trip & waypoint in view.' },
      { icon: 'psychology', title: 'AI Trip Timeline & Stops', text: 'Waypoints turned into a trip story.' },
      { icon: 'directions_car', title: 'Vehicle Management', text: 'From the daily car to the camper van.' },
    ],
    primaryCta: 'Visit wayventure.de',
    secondaryCta: 'Request an architecture case',
    imageAlt: 'Interface of the WayVenture travel companion app',
    status: 'Live at wayventure.de',
  },
  motto: {
    eyebrow: '// My personal motto',
    quote: 'Publish early, but publish complete.',
    text: 'Speed is worthless if the MVP breaks at the first real customer contact. We combine a fast time-to-market with reliable attention to detail.',
    pillars: [
      {
        badge: 'PILLAR 01',
        icon: 'rocket_launch',
        accent: 'brand',
        title: 'Publish Early',
        text: 'Don’t build in a vacuum for nine months: test hypotheses quickly with real users, secure valuable feedback and back up feature decisions.',
        points: [ 'Fast prototype releases', 'Real feedback loops from day one', 'Clear MVP prioritization' ],
      },
      {
        badge: 'PILLAR 02',
        icon: 'verified',
        accent: 'amber',
        title: 'Publish Complete',
        text: 'Minimal never means broken. Every release ships with working auth, clean error states, a consistent UI and well-considered security standards.',
        points: [ 'Thoughtful edge-case handling', 'Robust error handling & fallbacks', 'Polished ergonomics (mobile & web)' ],
      },
      {
        badge: 'FOUNDER ADVISORY',
        icon: 'lightbulb',
        accent: 'indigo',
        title: 'Interim CTO & MVP Scoping',
        text: 'Support for non-technical founders: make-or-buy decisions, tech stack selection and making sure the source code stays in your hands.',
        cta: 'Request founder consulting',
      },
      {
        badge: 'ORGANIZATION SCALING',
        icon: 'groups',
        accent: 'emerald',
        title: 'Dev Team & Process Setup',
        text: 'Building high-impact teams: clean branching strategies, CI/CD pipelines, agile rituals and technical interviews for new hires.',
        cta: 'Request team enablement',
      },
    ],
  },
  offers: {
    eyebrow: 'Clear packages & terms',
    icon: 'inventory_2',
    title: 'Transparent Web & Software Solutions',
    text: 'For founders, SMEs and service providers: no opaque agency hourly rates, but clear milestones and measurable results.',
    packages: [
      {
        tier: 'Starter',
        title: 'Static One-Pager',
        text: 'Perfect for campaigns, freelancer portfolios or product tests with a razor-sharp focus.',
        features: [ 'Extremely fast load times (<1s)', '100% GDPR compliant without cookies', 'Mobile-first ergonomics', 'Lead / contact form' ],
      },
      {
        tier: 'Dynamic',
        title: 'Interactive CMS Page',
        text: 'For growing businesses that want to maintain content, references and news themselves.',
        features: [ 'Lean headless CMS', 'Edit text & images without code', 'Interactive filters & animations', 'Domain, SSL & mail setup' ],
        featured: true,
      },
      {
        tier: 'Growth',
        title: 'Business Website',
        text: 'A comprehensive digital presence with multiple service pages and a search engine strategy.',
        features: [ 'Up to 5 individual subpages', 'SEO schema markup & metadata', 'Individual UI/UX concept', 'Editorial workflow & roles' ],
      },
      {
        tier: 'Full-Scale',
        title: 'Enterprise System',
        text: 'Custom portals, customer areas or system integrations with the highest level of security.',
        features: [ 'Complex roles & auth (OAuth)', 'API & third-party integration', '99+ Lighthouse performance score', 'Dedicated support & SLA' ],
      },
    ],
    requestCta: 'Request package',
    featuredCta: 'Choose package',
    featuredBadge: 'Recommended',
    custom: {
      title: 'Looking for custom software architecture or MVP development?',
      text: 'Do you need scalable C# .NET microservices, hybrid mobile apps or a well-founded zero-trust cloud infrastructure? Let’s discuss your requirements.',
      cta: 'Book an architecture call',
    },
  },
  aiConsulting: {
    eyebrow: 'No hype, just craft',
    icon: 'psychology',
    title: 'AI Consulting & Developer Coaching',
    text: 'Most AI workshops stop at superficial ChatGPT prompts. I show teams how autonomous agents and deterministic interfaces produce real code, without losing control.',
    tracks: [
      {
        badge: 'FOR BUSINESSES & TEAMS',
        icon: 'apartment',
        accent: 'brand',
        title: 'Agent Workflow Migration & AI Audit',
        text: 'We analyze existing development cycles and integrate AI agents safely into your toolchain – with strict attention to GDPR, IP protection and code quality metrics.',
        items: [
          { icon: 'query_stats', title: 'Engineering Bottleneck Audit', text: 'Where agents really save developer time (and where they hurt).' },
          { icon: 'policy', title: 'Governance & Privacy Compliance', text: 'Clear guidelines for Ollama, Claude Enterprise and OpenAI.' },
          { icon: 'speed', title: 'Hands-on MVP Deployment', text: 'A concrete pilot integration within days instead of months.' },
        ],
        cta: 'Book a strategy call',
      },
      {
        badge: 'DEVELOPER TO DEVELOPER',
        icon: 'terminal',
        accent: 'emerald',
        title: 'Mastering AI Agents: 1:1 Coaching',
        text: 'Learn how to use Claude Code, terminal agents and MCP servers to ship 5x faster while keeping 100% of the architectural control.',
        items: [
          { icon: 'code', title: 'Claude Code & CLI Agents', text: 'Structuring context windows, sub-tasking and branch hygiene.' },
          { icon: 'hub', title: 'Building Your Own MCP Servers', text: 'Connect your own databases & APIs directly to LLM agents.' },
          { icon: 'check_circle', title: 'TDD as an Agent Guardrail', text: 'Automated tests as a quality filter for AI-generated commits.' },
        ],
        cta: 'Request 1:1 coaching',
      },
    ],
  },
  experience: {
    eyebrow: 'Experience & stations',
    icon: 'history_edu',
    title: 'Career Path',
    text: 'Solid industry experience, scientific depth in distributed systems and self-driven product development.',
    items: [
      {
        title: 'Freelance Senior Developer & AI Ambassador',
        period: 'Since June 2026',
        text: 'Building scalable Next.js web systems and API backends. For an agency focused on AI development, I bring the principles of traditional software engineering into agentic workflows and MCP servers.',
        accent: 'brand',
      },
      {
        title: 'Founder & Lead Architect — WayVenture',
        period: 'Since April 2026',
        text: 'Building and running the mobile all-in-one travel companion app with digital travel pass, trip budget, AI trip timeline and vehicle management.',
        accent: 'amber',
      },
      {
        title: 'Full Stack Developer — Strauss GmbH & Co. KG',
        period: 'Since Oct. 2024',
        text: 'Developing and maintaining core microservices with C# .NET and Angular that gradually replace the functionality of a legacy system.',
        accent: 'indigo',
      },
      {
        title: 'Freelance Lead Dev: JagdTausch Marketplace MVP',
        period: 'July 2024 – Sept. 2025',
        text: 'Concept and turnkey delivery of the marketplace platform (PWA) for used hunting equipment, including real-time chat, filtering and an admin dashboard.',
        accent: 'slate',
      },
      {
        title: 'Working Student Full Stack — Reservix',
        period: 'Dec. 2021 – Sept. 2024',
        text: 'Building a reporting tool for theatres and event organizers that makes ticket sales analysis much easier. PHP, TypeScript, MongoDB, Terraform and Mercure.',
        accent: 'slate',
      },
      {
        title: 'Working Student & Bachelor Thesis — ECOPLAN GmbH',
        period: 'Sept. 2017 – Sept. 2021',
        text: 'Building and customizing a CRM system for multiple clients, including integration of the Swiss QR bill. Web services with Java EE on Tomcat.',
        accent: 'slate',
      },
    ],
    highlights: [
      {
        icon: 'school',
        eyebrow: 'M.Sc. Applied Computer Science',
        meta: '• Fulda University of Applied Sciences',
        title: 'Master’s thesis: Kubernetes Security & Zero Trust Architecture',
        text: 'Research on securing container infrastructures, workload isolation, service meshes (mTLS with Istio) and automated runtime security analysis.',
        href: '/Masterthesis.pdf',
      },
    ],
  },
  volunteering: {
    badge: 'Social responsibility & values',
    title: 'Volunteer Fire Department — Commitment & Reliability Under Pressure',
    text: 'For me, responsibility doesn’t end at the screen. Since 2018 I have been an active squad leader in the volunteer fire department (Fulda-Mitte 2018–2024, Hofbieber-Mitte since 2024).',
    values: [
      { label: 'Focus', value: 'Team spirit' },
      { label: 'Readiness', value: '24/7 reliability' },
      { label: 'Leadership', value: 'Clear communication' },
      { label: 'Resilience', value: 'Calm under load' },
    ],
    quoteLabel: '// Transfer to engineering',
    quote: 'On a call, just like during a critical production outage: clear priorities, complete trust in the team and decisive action without panic lead to success.',
    signature: 'Christian Dechant, squad leader',
  },
  faq: {
    eyebrow: 'Frequently asked questions',
    icon: 'help',
    title: 'Questions & Answers',
    text: 'The essentials at a glance – and if your question is missing, just write to me.',
    items: [
      {
        question: 'Who is Christian Dechant?',
        answer: 'Christian Dechant is a freelance senior full-stack developer and AI consultant based in Hofbieber near Fulda, Germany. He holds an M.Sc. in Applied Computer Science from Fulda University of Applied Sciences, has more than 9 years of software development experience, develops microservices with C# .NET at Strauss GmbH & Co. KG and is the founder of the travel app WayVenture.',
      },
      {
        question: 'Which services do you offer?',
        answer: 'Websites from one-pagers to enterprise systems, custom web and software development, AI consulting for introducing AI agents into development teams, 1:1 coaching for developers, and founder consulting from MVP scoping to interim CTO.',
      },
      {
        question: 'Which technologies do you work with?',
        answer: 'Frontend: Next.js, React, Nuxt, Vue.js and Angular. Backend: C# .NET, PHP (Laravel, Symfony), Node.js, Python and Java. Plus PostgreSQL, MySQL and MongoDB, Docker, Kubernetes, AWS and Azure, and AI tools such as Claude Code and MCP.',
      },
      {
        question: 'Do you work remotely or only in Fulda?',
        answer: 'Remote-first for clients in Germany, Austria, Switzerland and internationally, in German and English. On-site meetings in and around Fulda are possible by arrangement.',
      },
      {
        question: 'How much does a project cost?',
        answer: 'Every project is quoted individually. After a short initial call about goals and scope, you receive a transparent proposal with clear milestones instead of opaque hourly rates.',
      },
      {
        question: 'How quickly will I get a reply?',
        answer: 'I personally reply to requests via the contact form or e-mail within 24 hours. We agree on a possible start date in the initial call, based on scope and availability.',
      },
    ],
  },
  contact: {
    testimonials: [
      {
        name: 'Caroline Grabowski',
        role: 'JagdTausch',
        text: 'Great collaboration — always reliable, punctual, and passionate about his work. He took his time with everything and did a fantastic job!',
      },
      {
        name: 'Student representation for sensor technology, actuator technology & electronics',
        role: 'Darmstadt Technical University',
        text: 'Competent advice and reliable implementation of customer-specific requirements!',
        initials: 'TU',
      },
    ],
    eyebrow: 'Direct contact',
    title: 'Let’s discuss your project',
    text: 'Whether senior freelance capacity for your web & cloud project, tailored AI workflows or technical sparring: I will personally get back to you within 24 hours.',
    items: [
      { label: 'E-MAIL', text: contactEmail, href: `mailto:${ contactEmail }`, icon: 'send', accent: 'brand' },
      { label: 'LOCATION', text: 'Hofbieber / Hesse, Germany (remote-first)', icon: 'location_on', accent: 'brand' },
      { label: 'RESPONSE GUARANTEE', text: '< 24h response time', icon: 'schedule', accent: 'emerald' },
    ],
    form: {
      name: 'Your name *',
      namePlaceholder: 'e.g. Anna Schmidt',
      email: 'E-mail address *',
      emailPlaceholder: 'anna@company.com',
      scope: 'Project area',
      scopes: [
        { value: 'freelance', label: 'Freelance Web / Full-Stack (Next.js, C# .NET)' },
        { value: 'ai', label: 'AI Consulting / Agentic Workflows / MCP' },
        { value: 'package', label: 'Website package (One-Pager, CMS, Business)' },
        { value: 'coaching', label: '1:1 developer coaching' },
        { value: 'founder', label: 'Founder consulting / team setup' },
        { value: 'wayventure', label: 'WayVenture cooperation' },
      ],
      message: 'Short description & goals *',
      messagePlaceholder: 'What is your project about? What timeframe do you have in mind?',
      consent: [
        'I agree that my details will be processed to contact me and answer my request (',
        'Privacy Policy',
        ').',
      ],
      submit: 'Send request',
      sending: 'Sending …',
      success: 'Thank you! Your message has been sent. Christian Dechant will get back to you shortly.',
      rateLimited: 'Too many requests in a short time. Please try again in a few minutes or send an e-mail directly.',
      error: 'Sorry, something went wrong. Please try again or send an e-mail directly.',
    },
  },
  cookieBanner: {
    eyebrow: 'Cookies & privacy',
    title: 'Your privacy matters',
    text: [
      'This website only uses technically necessary storage, e.g. to remember your choice here. Optional services are only loaded with your consent, which you can withdraw at any time in the footer. Learn more in the ',
      'Privacy Policy',
      '.',
    ],
    acceptAll: 'Accept all',
    necessaryOnly: 'Necessary only',
    settings: 'Settings',
    save: 'Save selection',
    alwaysActive: 'Always active',
    categories: {
      necessary: {
        title: 'Necessary',
        text: 'Stores your cookie choice locally in your browser. The banner cannot work without it.',
      },
      statistics: {
        title: 'Statistics & external media',
        text: 'No such services are currently in use. New services will only be loaded after you consent.',
      },
    },
  },
  footer: {
    tagline: 'InterestedOWL · M.Sc. Applied Computer Science · Senior Full-Stack & Applied AI',
    imprint: 'Imprint',
    privacy: 'Privacy',
    languageLabel: 'Choose language',
    cookieSettings: 'Cookie settings',
    rights: 'All rights reserved.',
    status: 'Available for selected new projects',
  },
  wayventurePage: {
    metaTitle: 'WayVenture — Travel Planner App Built by Christian Dechant',
    metaDescription: 'WayVenture is an independent travel planner app for road trips, camper journeys and spontaneous getaways, with a digital travel pass, AI trip timelines, budgeting and vehicle management. Built and shipped by Christian Dechant.',
    back: 'Back to the homepage',
    badge: 'Founder project · Live product',
    title: 'WayVenture',
    subtitle: 'Your smart travel planner – from the planning to the memory.',
    intro: 'WayVenture is a mobile-first travel planner app I designed and built independently, alongside my freelance development work. It helps travelers leave quickly and stay organized without preparation overhead, whether that’s a spontaneous weekend road trip or a fully planned multi-country camper journey.',
    tryCta: 'Try WayVenture for free',
    storyTitle: 'Why I built WayVenture',
    story: [
      'Most travel apps assume a trip is planned weeks in advance. In practice, a lot of the best trips start with almost no planning at all: a free weekend, a full tank of fuel and a rough direction. WayVenture treats spontaneous trips and planned trips as equally first-class: a spontaneous trip can be created in a single step, with the name, start date, budget and status filled in automatically, while a planned trip gets a full itinerary with waypoints and country-aware travel advisories.',
      'The product is guided by a few simple principles: mobile-first thinking, fast access to relevant information, minimizing preparation friction, staying offline-friendly where possible, and shipping features incrementally instead of chasing a big-bang launch. Underneath is a properly engineered stack: a Next.js and TypeScript frontend, a Django REST Framework backend, Stripe for subscription billing and a containerized Docker deployment with an eye on security and scalability from day one.',
    ],
    featuresTitle: 'What WayVenture does',
    featuresText: 'An all-in-one travel app: plan the trip, live through it, and keep the memory.',
    features: [
      { icon: 'badge', title: 'Digital Travel Pass', description: 'Every country you visit gets stamped into a digital passport, so your travel history becomes something you can actually look back on.', badge: 'USP' },
      { icon: 'payments', title: 'Trip Budget Planner', description: 'Track spending per trip and per waypoint, so you always know what a spontaneous detour is going to cost before you take it.' },
      { icon: 'map', title: 'Waypoints & Travel Notices', description: 'Add waypoints on the fly, get country-specific travel advisories, and share a route via link with fellow travelers.' },
      { icon: 'auto_awesome', title: 'AI Trip Timeline', description: 'An AI-generated summary turns raw waypoints and dates into a readable story of the trip, automatically.', badge: 'AI' },
      { icon: 'group', title: 'Sharing & Invites', description: 'Share a trip with shared-link or invite-link access, so friends and family can follow along without an account.' },
      { icon: 'directions_car', title: 'Vehicle Management', description: 'Keep vehicles, from the daily car to the camper van, attached to the trips they belong to.' },
    ],
    screenshotAlt: 'Screenshot of the WayVenture travel app showing trip planning, digital travel pass and budget overview',
    roadmapTitle: 'What’s next',
    roadmapText: 'WayVenture ships incrementally. Here is what’s on the roadmap:',
    upcoming: [
      { icon: 'favorite', title: 'Community Features' },
      { icon: 'dashboard_customize', title: 'Creator Mode' },
      { icon: 'checklist', title: 'Equipment Checklists' },
      { icon: 'camping', title: 'Camp Spots' },
      { icon: 'smart_toy', title: 'AI Travel Agent' },
      { icon: 'photo_album', title: 'Trip Photobook' },
    ],
    vaultTitle: 'Document Safe',
    vaultSubtitle: '(Digital Vault)',
    vaultText: 'A future differentiator on the roadmap: a secure, encrypted place for travel and vehicle documents, with offline availability, expiration reminders, travel checklists and OCR support, so passports, visas and vehicle papers are one tap away even without a connection.',
    faqTitle: 'Frequently asked questions',
    faq: [
      {
        question: 'What is WayVenture?',
        answer: 'WayVenture is a mobile-first travel companion app for planning and living through road trips and spontaneous getaways. It combines a digital travel pass, trip budgeting, AI-generated trip timelines, waypoint-based travel advisories and vehicle management in a single all-in-one travel app.',
      },
      {
        question: 'Who built WayVenture?',
        answer: 'WayVenture is an independent product designed and built by Christian Dechant, a full-stack developer, as a self-initiated venture alongside his freelance work.',
      },
      {
        question: 'What makes WayVenture different from other travel planners?',
        answer: 'WayVenture supports both planned trips and spontaneous trips as first-class citizens. A spontaneous trip can be created in a single step with everything else – name, start date, budget – filled in automatically, while planned trips get a full itinerary with waypoints and country-aware travel advisories.',
      },
      {
        question: 'Is WayVenture free to use?',
        answer: 'WayVenture offers a free tier alongside paid Weltenbummler and Globetrotter tiers that unlock features like per-waypoint travel advice and higher usage limits.',
      },
      {
        question: 'What is coming next for WayVenture?',
        answer: 'The roadmap includes community features, a creator mode, equipment checklists, camp spot discovery, an AI travel agent, a trip photobook and a “Document Safe” for securely storing travel and vehicle documents with OCR and expiry reminders.',
      },
      {
        question: 'Where can I try WayVenture?',
        answer: 'WayVenture is live at wayventure.de in both German and English, with no credit card required to start.',
      },
    ],
    visitCta: 'Visit WayVenture',
    talkCta: 'Talk to me about it',
  },
  notFound: {
    title: 'Page not found',
    text: 'The page you requested does not exist (anymore). Maybe the homepage helps.',
    cta: 'Go to the homepage',
  },
  imprint: {
    metaTitle: 'Imprint | Christian Dechant',
    metaDescription: 'Legal notice and provider identification of Christian Dechant in accordance with § 5 DDG.',
    eyebrow: 'Legal',
    title: 'Imprint',
    intro: 'This English version is provided for convenience. The German version is legally binding.',
    updated: legalUpdated,
    sections: [
      {
        heading: 'Information according to § 5 DDG',
        paragraphs: [ 'Christian Dechant\nLangenbieberer Str. 14\n36145 Hofbieber\nGermany' ],
      },
      {
        heading: 'Contact',
        paragraphs: [ `E-mail: ${ contactEmail }` ],
      },
      {
        heading: 'VAT',
        paragraphs: [ 'Small business within the meaning of § 19 UStG (German VAT Act). No VAT is charged or shown.' ],
      },
      {
        heading: 'Responsible for content according to § 18 (2) MStV',
        paragraphs: [ 'Christian Dechant\nLangenbieberer Str. 14\n36145 Hofbieber' ],
      },
      {
        heading: 'Consumer dispute resolution',
        paragraphs: [ 'I am neither willing nor obliged to participate in dispute resolution proceedings before a consumer arbitration board.' ],
      },
      {
        heading: 'Liability for content',
        paragraphs: [
          'The contents of these pages were created with the utmost care. However, I cannot guarantee the accuracy, completeness and timeliness of the content. As a service provider, I am responsible for my own content on these pages under general law in accordance with § 7 (1) DDG.',
          'According to §§ 8 to 10 DDG, however, I am not obliged as a service provider to monitor transmitted or stored third-party information or to investigate circumstances that indicate illegal activity. Obligations to remove or block the use of information under general law remain unaffected. Liability in this respect is only possible from the time of knowledge of a specific infringement. As soon as I become aware of such infringements, I will remove this content immediately.',
        ],
      },
      {
        heading: 'Liability for links',
        paragraphs: [
          'This website contains links to external third-party websites over whose content I have no influence. Therefore, I cannot accept any liability for this third-party content. The respective provider or operator of the linked pages is always responsible for their content. The linked pages were checked for possible legal violations at the time of linking. Illegal content was not recognizable at the time of linking.',
          'Permanent monitoring of the content of linked pages is not reasonable without concrete evidence of an infringement. As soon as I become aware of legal violations, I will remove such links immediately.',
        ],
      },
      {
        heading: 'Copyright',
        paragraphs: [
          'The content and works created by the site operator on these pages are subject to German copyright law. Duplication, processing, distribution and any kind of exploitation outside the limits of copyright law require the written consent of the respective author or creator. Downloads and copies of this site are only permitted for private, non-commercial use.',
          'Insofar as the content on this site was not created by the operator, the copyrights of third parties are respected. Should you nevertheless become aware of a copyright infringement, please let me know. As soon as I become aware of legal violations, I will remove such content immediately.',
        ],
      },
    ],
  },
  privacy: {
    metaTitle: 'Privacy Policy | Christian Dechant',
    metaDescription: 'Information on the processing of personal data on christiandechant.de in accordance with the GDPR.',
    eyebrow: 'Legal',
    title: 'Privacy Policy',
    intro: 'Protecting your personal data is important to me. In accordance with Art. 13 GDPR, I inform you below which data is processed when you visit this website, for what purpose and on which legal basis. This English version is provided for convenience; the German version is legally binding.',
    updated: legalUpdated,
    sections: [
      {
        heading: '1. Controller',
        paragraphs: [
          'The controller responsible for data processing on this website within the meaning of the General Data Protection Regulation (GDPR) is:',
          `Christian Dechant\nLangenbieberer Str. 14\n36145 Hofbieber\nGermany\nE-mail: ${ contactEmail }`,
          'No data protection officer has been appointed, as there is no legal obligation to do so.',
        ],
      },
      {
        heading: '2. Legal bases',
        paragraphs: [ 'I process personal data on the following legal bases:' ],
        list: [
          'Art. 6 (1) (a) GDPR – consent',
          'Art. 6 (1) (b) GDPR – performance of a contract and pre-contractual measures',
          'Art. 6 (1) (c) GDPR – compliance with a legal obligation',
          'Art. 6 (1) (f) GDPR – legitimate interests',
          '§ 25 (1) and (2) TDDDG – storing and accessing information on your device',
        ],
      },
      {
        heading: '3. Hosting',
        paragraphs: [
          'This website is hosted by Hetzner Online GmbH, Industriestr. 25, 91710 Gunzenhausen, Germany. When you access the website, the server log files listed below are processed on the host’s servers.',
          'The host is used in the interest of providing this website securely, quickly and efficiently (Art. 6 (1) (f) GDPR). A data processing agreement in accordance with Art. 28 GDPR has been concluded with the host.',
        ],
      },
      {
        heading: '4. Server log files',
        paragraphs: [ 'Each time this website is accessed, the web server automatically records information transmitted by your browser:' ],
        list: [
          'IP address of the requesting device',
          'date and time of access',
          'requested page or file and HTTP status code',
          'amount of data transferred',
          'referrer URL (previously visited page)',
          'browser type, browser version and operating system (user agent)',
        ],
        subsections: [
          {
            heading: 'Purpose, legal basis and storage period',
            paragraphs: [
              'This processing is necessary to deliver the website, ensure its stability and security and prevent misuse. The legal basis is Art. 6 (1) (f) GDPR. The data is not merged with other data sources. The log files are deleted as soon as they are no longer required for these purposes.',
            ],
          },
        ],
      },
      {
        heading: '5. Contact form and e-mail',
        paragraphs: [
          'If you send me a request via the contact form or by e-mail, I process the data you provide (name, e-mail address, selected project area and your message) in order to handle your request and reply to you. After submitting the form, you receive an automatic confirmation with a copy of your details at the e-mail address you entered.',
          'The legal basis is Art. 6 (1) (b) GDPR if your request relates to the initiation or performance of a contract, and otherwise Art. 6 (1) (f) GDPR (legitimate interest in answering requests).',
          'The e-mails are sent via the SMTP server of my e-mail provider, which processes the data as a processor. The data is not otherwise passed on to third parties.',
          'Your data will be deleted once your request has been fully processed, unless statutory retention obligations (e.g. for business letters under § 257 HGB or § 147 AO) prevent this.',
        ],
      },
      {
        heading: '6. Cookies and consent management',
        paragraphs: [
          'This website does not use any tracking or advertising cookies and currently does not embed any optional third-party services. On your first visit, a banner asks for your consent to optional services, so that any new service is only loaded after you agree.',
          'Your choice (granted categories, version and time) is stored exclusively in your browser’s local storage (localStorage, key “cd-consent”) and is not transmitted to my server or third parties. You will be asked again after 12 months.',
          'This storage is strictly necessary to respect your decision (§ 25 (2) no. 2 TDDDG); the legal basis for the processing is Art. 6 (1) (c) GDPR in conjunction with Art. 7 (1) GDPR. You can change or withdraw your choice at any time via the “Cookie settings” link in the footer, or remove it by deleting the site data in your browser.',
        ],
      },
      {
        heading: '7. Fonts and icons',
        paragraphs: [
          'The fonts (Geist, JetBrains Mono) and icons (Material Symbols) used on this website are served locally from my own server. No connection to servers of Google or other third parties is established.',
        ],
      },
      {
        heading: '8. Links to external websites and social networks',
        paragraphs: [
          'This website contains simple links to external services, e.g. LinkedIn, XING, GitHub, wayventure.de and jagdtausch.de. These are not embedded plugins: merely visiting this website does not transfer any data to these providers. Only when you click a link are you taken to the respective provider’s website, where its privacy policy applies.',
        ],
      },
      {
        heading: '9. SSL/TLS encryption',
        paragraphs: [
          'For security reasons and to protect the transmission of confidential content, such as requests sent via the contact form, this website uses TLS encryption. You can recognize an encrypted connection by “https://” in your browser’s address bar.',
        ],
      },
      {
        heading: '10. Your rights',
        paragraphs: [ 'You have the following rights regarding your personal data:' ],
        list: [
          'access to the processed data (Art. 15 GDPR)',
          'rectification of inaccurate data (Art. 16 GDPR)',
          'erasure of your data (Art. 17 GDPR)',
          'restriction of processing (Art. 18 GDPR)',
          'data portability (Art. 20 GDPR)',
          'withdrawal of consent with effect for the future (Art. 7 (3) GDPR)',
        ],
        subsections: [
          {
            heading: 'Right to object (Art. 21 GDPR)',
            paragraphs: [
              'Where I process your data on the basis of legitimate interests (Art. 6 (1) (f) GDPR), you have the right to object to this processing at any time on grounds relating to your particular situation.',
            ],
          },
          {
            heading: 'Right to lodge a complaint with a supervisory authority',
            paragraphs: [
              'You have the right to lodge a complaint with a data protection supervisory authority (Art. 77 GDPR). The competent authority is: Der Hessische Beauftragte für Datenschutz und Informationsfreiheit, Gustav-Stresemann-Ring 1, 65189 Wiesbaden, Germany, https://datenschutz.hessen.de',
            ],
          },
          {
            heading: 'Exercising your rights',
            paragraphs: [ `An informal message to ${ contactEmail } is sufficient to exercise your rights.` ],
          },
        ],
      },
      {
        heading: '11. Obligation to provide data and automated decision-making',
        paragraphs: [
          'You are under no legal or contractual obligation to provide me with personal data. Without a name and e-mail address, however, I cannot answer a request sent via the contact form. There is no automated decision-making, including profiling (Art. 22 GDPR).',
        ],
      },
      {
        heading: '12. Changes to this privacy policy',
        paragraphs: [
          'I update this privacy policy whenever changes to the website or the legal situation make it necessary. The version published here applies.',
        ],
      },
    ],
  },
};
